CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  account_id TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  email_verified INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exhibits (
  id TEXT PRIMARY KEY,
  owner_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT 'Cara Mia',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS widgets (
  id TEXT PRIMARY KEY,
  exhibit_id TEXT NOT NULL REFERENCES exhibits(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('canvas', 'wordbox', 'music', 'sticker', 'gif')),
  x REAL NOT NULL DEFAULT 120,
  y REAL NOT NULL DEFAULT 120,
  width REAL NOT NULL DEFAULT 260,
  height REAL NOT NULL DEFAULT 180,
  z_index INTEGER NOT NULL DEFAULT 1,
  data TEXT NOT NULL DEFAULT '{}',
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shares (
  id TEXT PRIMARY KEY,
  exhibit_id TEXT NOT NULL REFERENCES exhibits(id) ON DELETE CASCADE,
  target_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('viewer', 'collaborator')),
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (exhibit_id, target_user_id)
);

CREATE INDEX IF NOT EXISTS idx_widgets_exhibit ON widgets(exhibit_id);
CREATE INDEX IF NOT EXISTS idx_shares_target ON shares(target_user_id);
